### ISSUE TITLE
will windows/iis platform be supported?

### ISSUE THREAD

**Issue by artknight** [letsencrypt/lets-encrypt-preview#288] opened 2015-03-18 15:06 UTC

**Comment by kuba** [comment] 2015-03-18 15:07
duplicate of #116, please use "search"

**Comment by artknight** [comment] 2015-03-18 15:13
sorry, from reading the above it is not apparent to me that windows will be supported from the get-go!

**Comment by artknight** [comment] 2015-03-18 15:18
Also, my company is launching a site in a few weeks and I would hate to purchase an SSL cert in the wake of the official release of letsencrypt. Is there anything i can use aleady for Win Server 2008?

**Comment by schoen** [comment] 2015-03-20 21:03
Hi @artknight, unfortunately public issuance of certs isn't expected until sometime around the middle of the year, so if you need a cert in a few weeks you should plan to obtain it from another CA.

We also don't have an estimate about when the Windows integration will be working, but we may be able to offer an update on that soon (or perhaps a pointer to a codebase).

**Comment by artknight** [comment] 2015-03-20 21:04
awesome, thanks!

**Closed** 2015-04-27 21:52 UTC
Labels: question
