### ISSUE TITLE
running as root and reading about EVERY file in /etc

### ISSUE THREAD

**Issue by ThomasWaldmann** [letsencrypt/lets-encrypt-preview#169] opened 2015-01-20 20:00 UTC
I did an strace on a letsencrypt run (see also #168) and found that it opens and reads about every file that lives in /etc (+ some more dotfiles).

Including, but not limited to, a lot of files that contain plaintext passwords, sudo configuration and other sensitive information that letsencrypt does definitely not need for operation. I expected it to look at apache/webserver stuff, but it also read ALL my wireless passwords (for example).

What would you think of a tool behaving like this?

Update: just to clarify: it is not the letsencrypt code that reads all the files, but the default behaviour of the augeas config parsing/editing library that is used by letsencrypt.

**Comment by jdkasten** [comment] 2015-01-20 20:03
See #168... it is on the TODO list.  With a clear TODO in the code.  This project is several months from release and is in no way shape or form meant to be run in a production environment.  The code is here for development only.

**Comment by ThomasWaldmann** [comment] 2015-01-20 20:18
well, maybe some devs also do not feel too comfortable with tools that access a lot of unrelated and sensitive stuff on their development machines. I'll have a look whether I can improve that...

**Comment by jdkasten** [comment] 2015-01-20 21:30
Found a fix.. I will apply the patch shortly.

**Comment by jdkasten** [comment] 2015-01-20 22:32
I believe #170 completely addresses this issue.  Augeas by default loads all of its parsing modules and typical files.  When I first wrote that code... (a few years ago) I looked up the solution NO_MODL_AUTOLOAD, but couldn't implement it yet because I was still relying on Augeas for default transforms of common Apache files.  I marked it as a TODO and moved on.

Now that we manually handle all transforms as required for atypical installations and for unit testing purposes, the TODO was easily remedied.

I decided to take it on immediately myself, because I figured I had more background handling Augeas, I already had a pretty good idea of the issue having looked it up before, and felt that it probably warranted immediate fixing rather than waiting to fix it at the end of my current branch (revising the augeas_configurator)

I ran strace and I believe I confirmed that we now only touch files directly that are referenced from the Apache root configuration and files located in apache2/sites-available.  Thanks for prompting the issue.  I am going to run some more tests to make sure that Augeas is still properly excluding files like *~ and will merge the branch once I am done.  (I am also writing unit tests for the augeas_configurator in my developing branch but that will come later)

Please let me know if there are any other issues sorry for any inconvenience it may have caused.

James

**Comment by ThomasWaldmann** [comment] 2015-01-21 00:04
great, thanks for fixing! just close my related PR when you're done with it.

**Comment by jdkasten** [comment] 2015-01-21 06:18
Fixed in #170! Thanks @ThomasWaldmann!

**Closed by jdkasten** 2015-01-21 06:18 UTC
Labels: duplicate
