### ISSUE TITLE
Make sure the request-for-email UI is well designed

### ISSUE THREAD

**Issue by pde** [letsencrypt/lets-encrypt-preview#410] opened 2015-05-12 22:30 UTC
The interactive mode for the client needs to ask for an email.  It should allow the user to not enter one, but in that case it should make it's warned them that they will miss notifications about failures to renew, cert expiries.

In command-line mode, we may want to make the email address a mandatory parameter, with a magic value like "Im-crazy-no-emergency-email-notifications" that can be used to not enter one.

All of this will need to be carefully polished to ensure that users have a good experience with these aspects of the client's behaviour.

**Comment by jsha** [comment] 2015-05-22 16:42
Closing as dupe of #414.

**Closed by jsha** 2015-05-22 16:42 UTC
Labels: ui / ux
